### ISSUE TITLE
Any way to install/use this for CC?

### ISSUE THREAD

**Issue by hybridherbst** [fnordware/SuperPNG#10]
I can't figure out how to use this plugin in Photoshop CC - any info on whether that is still supported? Seems they are trying to run everything through that Extension Manager thing now.

Also, I found a couple forum posts mentioning the same issue (not getting it to run in anything newer than Photoshop CS3). 

It seems other plugins (e.g. http://www.flamingpear.com/ps-win-other-install.html) are still working in CC 2017 & 2018, so it seems it's possible in general, but is it for SuperPNG?

**Comment by born2excite** [comment]
Your question is vague, you don't give specific information so it's difficult to understand what you want. For example, when you ask about installing "this plugin" what plugin are you talking about? And, which Photoshop version??? 

I have to guess you're asking about SuperPNG so if that's what you want, all you need to do is:

Copy "SuperPNG.8bi" to plugins folder:
 - C:\Program Files\Adobe\Adobe Photoshop CC 2018\Plug-ins\SuperPNG.8bi
 - C:\Program Files\Adobe\Adobe Photoshop CC 2017\Plug-ins\SuperPNG.8bi

**Comment by hybridherbst** [comment]
These is the Issues section for the SuperPNG repository, or not? That's why I didn't explicitly state that it's about this plugin. Also, I wrote that the question is about CC 2017 and CC 2018.

After copying the plugin to these folders, where does it appear in the Photoshop UI? I tried what you are suggesting already (of course before posting this question, sorry if the question was not exact enough), and it doesn't seem to be working (SuperPNG does not show up anywhere in the Photoshop UI or on export).

Have you actually tried this and is it working for you?

**Comment by born2excite** [comment]
Just a friendly comment, always ask detailed questions to get the best answer with the least amount of trouble. Yes, SuperPNG works perfectly for me in both Photoshop CC 2018 and 2017 (I use them both on my PC)

All you have to do is go to File -> Save As -> Open the drop-down box to select SuperPNG (see attached screenshots for more details)
![superpng 1](https://user-images.githubusercontent.com/10362816/41696855-89076a7e-7559-11e8-8d90-548a9b8bedee.jpg)
![superpng 2](https://user-images.githubusercontent.com/10362816/41696860-92ba818c-7559-11e8-9dbd-e16ed4528e45.jpg)
![superpng 3](https://user-images.githubusercontent.com/10362816/41696872-9b194d9a-7559-11e8-8482-e51c8a56855d.jpg)

**Comment by born2excite** [comment]
Unfortunately, SuperPNG **does not** show up as an option when using the export function.

**Comment by 0ldM4cM4n** [comment]
Hello. I continue to use SuperPNG with Adobe Photoshop CC 2019 20.0.6 under Catalina on a 5K 27" i7 2017 iMac. I was just wondering if the bug will ever be fixed which causes the error message "Brendan is an idiot", which I understand is a reference to the developer Brendan Bolles. Thank you.

**Comment by TamersaysHi** [comment]
for show import options press SHIFT while opening
thanks fnord!

**Comment by hybridherbst** [comment]
Seems I forgot to close this - the above suggestion regarding "Save a copy" is still correct for the latest CC versions.
