### ISSUE TITLE
Building SuperPNG with Visual Studio 2015 Community Edition

### ISSUE THREAD

**Issue by nkoding** [fnordware/SuperPNG#7]
Hi,

I'd like to build SuperPNG with VS 2015 CE. Can you please provide another project?

After auto converting the VC++ projects I tried to import all of the projects in the repo and did not succeed due to unreadable resource files, dependencies etc.

Any help would be appreciated.

thx in advance

**Comment by fnordware** [comment]
Are you starting with the project in SuperPNG/vc/vc12? That was made with Visual Studio 2013 CE.

**Comment by nkoding** [comment]
OK, tried opening and building the vc12 project, I have set up a new Win 10 64 VM with just git and VS 2013 installed.

I cloned the repo, copied the photoshop sdk into the ext folder and got the following errors cloning external modules:
- updating external modules failed at pngquant module (so I cloned it manually, with the msvc branch and without it, as the pngquant readme says, but still getting compile errors)
- SuperPNG_x64.rc cannot be read (but it doesn't produce compile errors so this is probably not important)
- libpngquant cannot be built because of the MS compiler i think. I tried the msvc branch, but no success either.
- sources from src/photoshop do not appear in the solution

Am I doing something wrong here and if so, how is it done right?

**Comment by fnordware** [comment]
Yep, ext/pngquant-msvc was failing because Kornel killed his old msvc branch (which I was using) and started a new one, making the old commit inaccessible. I tried his latest stuff, but was not able to get it to build in vc12 (Visual Studio Express 2013). So what I did is resurrect that old branch under my own fork and added it as another submodule which the vc12 projects now point to. So re-clone everything and hopefully you'll have better luck.

**Comment by nkoding** [comment]
Thanx a lot! I'll try tomorrow and post the results here.

**Comment by nkoding** [comment]
Good morning,
I just tried to build with a new repo clone and it works like a charm :)

Thank you, Brendan, all issues are solved - even the files from /src/photoshop I thought were not listed. But they are linked in the SuperPNG project under "Project properties ->Linker->Additional Library Directories" and appear directly in the SuperPNG project's root.

Have  a nice day!

**Comment by fnordware** [comment]
Glad to hear it. Thanks for posting the issue.

**Comment by nkoding** [comment]
just wanted to add that it's building in Visual Studio 2015 CE as well.
